config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: "homes#top"
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorite, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationsips, only: [:create, :destroy]
    get "followings" => "relationsips#followings", as: "followings"
    get "followers" => "relationsips#followers", as: "followers"
  end

  resources :groups, only: [:new, :index, :show, :create, :edit, :update]

  get "search" => "searches#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  # RelationshipモデルはスペルミスでRelationsipになってしまっている

  has_many :active_relationships, class_name: "Relationsip", foreign_key: "follower_id", dependent: :destroy
  # has_manyの後ろに架空のわかりやすい名前のテーブルを記述、 class_nameで既存のRelationshipモデルのfollowe_idと関連していることを記述する。
 
  has_many :followings, through: :active_relationships, source: :followed
  # has_manyの後ろに架空のわかりやすい名前のテーブルを記述、throughで上で定義したactive_relationshipsを通って関連付けすることを定義。
  # その際にsourceでactive_relationshipsに関連しているRelationshipモデルで定義したfollowedを参照していることを記述。
  
  # ここまででフォローの関連付けが完了。
  # -----------------------------------------------------------------
  # ここからフォロワーの関連付け

  has_many :passive_relationships, class_name: "Relationsip", foreign_key: "followed_id", dependent: :destroy
  # has_manyの後ろに架空のわかりやすい名前のテーブルを記述、class_nameで既存のRelationshipモデルのfollowed_idと関連していることを記述する。

  has_many :followers, through: :passive_relationships, source: :follower
  # has_manyの後ろに架空のわかりやすい名前のテーブルを記述、throughで上で定義したpassivi_relationshipsを通って関連付けすることを定義。
  # その際にsourceでpassive_relationshipsに関連しているRelationshipモデルで定義したfollowerを参照していることを記述。

  # ここまででフォロワーの関連付けが完了。

  has_many :group_users, dependent: :destroy
  # これはグループ機能のリレーション
  
  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  # 指定したユーザーをフォローする
  def follow(user)
    active_relationships.create(followed_id: user.id)
  end

  # 指定したユーザーのフォローを解除する
  def unfollow(user)
    active_relationships.find_by(followed_id: user.id).destroy
  end

  # 指定したユーザーをフォローしているかどうかを判定
  def following?(user)
    followings.include?(user)
  end
  
  
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end


  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
       User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
       User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
       User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
       User.where("name LIKE?","%#{word}%")
    else
       User.all
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    if @books.any?
      show_book = @books[0]
      @show_user = User.find(show_book.user_id)
      @book = Book.new
    else
      @show_user = User.find(params[:id])
      @book = Book.new
    end
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    # ensure_correct_user
    @user = User.find(params[:id])
  end

  def update
    # ensure_correct_user
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数<%= user.followings.count%></td> 
        <td>フォロワー数<%= user.followers.count %></td>
        <% if current_user != user %>
          <% if current_user.following?(user) %>
            <td><%= link_to "フォロー外す", user_relationsips_path(user.id), method: :delete %></td>
          <% else %>
            <td><%= link_to "フォローする", user_relationsips_path(user.id), method: :post %></td>
          <% end %>
        <% else %>
          <td colspan="1"></td>
        <% end %>
        <td><%= link_to 'Show', user_path(user.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to user.followings.count, user_followings_path(user) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to user.followers.count, user_followers_path(user) %></th>
  </tr>
</table>

<div class='row'>
  <% if current_user != user %>
    <% if current_user.following?(user) %>
      <td><%= link_to "フォロー外す", user_relationsips_path(user.id), class: "btn btn-outline-secondary btn-block", method: :delete %></td>
    <% else %>
      <td><%= link_to "フォローする", user_relationsips_path(user.id), class: "btn btn-outline-secondary btn-block", method: :post %></td>
    <% end %>
  <% else %>
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render 'info', user: current_user %>

      <h2 class="mt-3">New book</h2>
      <%= render '/books/form', book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <%=link_to "グループを作成する",new_group_path %> | 
      <%=link_to "グループ一覧",groups_path %>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @show_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>